# Generated by Django 4.2.7 on 2023-12-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stand_up_admin', '0002_about_address_en_about_address_ru_about_address_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
