# Generated by Django 4.2.7 on 2023-12-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stand_up_admin', '0003_alter_banner_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food_Menu',
        ),
    ]
